#!/bin/bash -x

for gov in /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor
do
    echo performance | sudo tee -a $gov
done

echo performance | sudo tee -a /sys/devices/57000000.gpu/devfreq/57000000.gpu/governor

# Note: you cannot echo invalid values into these files - try it and it'll simply be rejected.
cat /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor
cat /sys/devices/57000000.gpu/devfreq/57000000.gpu/governor

cd /usr/src/tensorrt/bin

for i in {1..3}
do
    timeout 2s tegrastats
    time ./sample_uff_ssd_rect
    timeout 2s tegrastats
    sleep 60
done

sudo reboot now
