#!/bin/bash -x

cd /usr/src/tensorrt/bin

# Note: you cannot echo invalid values into these files - try it and it'll simply be rejected.
cat /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor
cat /sys/devices/57000000.gpu/devfreq/57000000.gpu/governor

for gov in /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor
do
    echo performance | sudo tee -a $gov
done

echo "CPUs set to performance"
timeout 2s tegrastats
time ./sample_uff_ssd_rect
timeout 2s tegrastats
sleep 60

echo performance | sudo tee -a /sys/devices/57000000.gpu/devfreq/57000000.gpu/governor

echo "CPUs and GPU set to performance"
timeout 2s tegrastats
time ./sample_uff_ssd_rect
timeout 2s tegrastats
sleep 60

echo nvhost_podgov | sudo tee -a /sys/devices/57000000.gpu/devfreq/57000000.gpu/governor
echo 921600000 | sudo tee -a /sys/devices/57000000.gpu/devfreq/57000000.gpu/min_freq

echo "CPUs set to performance, GPU governor set to normal and GPU min_freq set to max"
timeout 2s tegrastats
time ./sample_uff_ssd_rect
timeout 2s tegrastats
sleep 60

sudo jetson_clocks

echo "All clocks etc. set to max with jetson_clocks"
timeout 2s tegrastats
time ./sample_uff_ssd_rect
timeout 2s tegrastats
sleep 60

sudo reboot now
